### ISSUE TITLE
I have opened modbusRTUslave example. During compiling Threre is error about RS485.h file.

### ISSUE THREAD

**Issue by cbutani** [IndustrialShields/arduino-Tools40#10]
I have opened modbusRTUslave example. During compiling Threre is error about RS485.h file.

**Comment by jordicasals** [comment]
Hello @cbutani

The RS485.h library is included into the IndustrialShields devices boards:
https://www.industrialshields.com/blog/industrial-shields-blog-1/post/installing-the-industrial-shields-boards-in-the-arduino-ide-63

If you are not using an IndustrialShields device you might change RS485 for any other HardwareSerial (Serial1, Serial2, ...)
