### ISSUE TITLE
Error : 'MODBUS_TCP_ADU_SIZE' was not declared in this scope 

### ISSUE THREAD

**Issue by DLuffy999** [IndustrialShields/arduino-Tools40#12]
I have an error message from ModbusTCPMasterReadInputRegisters example.
I can use the Arduino Yun only. 
I am in Mongolia, I can not buy other devices and arduino ethernet shield.
How can I fix the error?
I am an arduino beginer, please let me know the solution as possible as detailly(with fixing code).

Below is full error message.

In file included from C:\arduino_coding\modbus_TCP_test02\ModbusTCPMasterReadInputRegisters\ModbusTCPMasterReadInputRegisters.ino:19:0:

ModbusTCPMaster.h:37:16: error: 'MODBUS_TCP_ADU_SIZE' was not declared in this scope

   uint8_t _adu[MODBUS_TCP_ADU_SIZE];

                ^

exit status 1
'MODBUS_TCP_ADU_SIZE' was not declared in this scope

**Comment by jordicasals** [comment]
Dear @DLuffy999 

we don't provide support for the Yun board.

You can try to disable the `ifdef` clause from `ModbusTCP.h` header file. Also remember to remove the related `endif`.
