### ISSUE TITLE
Example projects do not compile

### ISSUE THREAD

**Issue by dandamron** [IndustrialShields/arduino-Tools40#16]
ModbusTCPSlave does not compile - 
Arduino\libraries\arduino-Tools40-master\src/ModbusTCPSlave.h:28:16: error: 'MODBUS_TCP_ADU_SIZE' was not declared in this scope
   uint8_t _adu[MODBUS_TCP_ADU_SIZE];
                ^~~~~~~~~~~~~~~~~~~

**Comment by jordicasals** [comment]
Duplicate of #12

**Comment by dandamron** [comment]
This does not solve the problem. I'm compiling for a esp Plc 19R
Saying it's the same problem for a previous ticket number 12, and then at the end of number 12 saying we don't provide support for that board is not solving the problem.

**Comment by dandamron** [comment]
I'm sorry, saying that this is the same as #12, and closing this issue is not right.
If you look at #12, the user was using an unsupported board, and because of that, the question was not answered.  I'm compiling for an ESP PLC 19R. which IS supported.
Please re-open and answer the question rather than saying its a duplicate.
Sorry for the duplicate comments, one done on phone, one done on PC

**Comment by jordicasals** [comment]
Hi @dandamron 

you are right, the ESP32PLC was not in the supported devices list.

Now it should be solved.

**Comment by dandamron** [comment]
Thank you. I will try compiling later this am.

**Comment by dandamron** [comment]
I have confirmed the issues I was having are now fixed.  Thank you.
