### ISSUE TITLE
Issues with industrialshields/hardware/esp32/2.0.7/libraries/RS485

### ISSUE THREAD

**Issue by ganehag** [IndustrialShields/arduino-Tools40#21]
Hi,

I tried to implement a Modbus RTU master on a 10IOs using the Industrial Shields specific RS485 library. However I ran into two issues.

1. The RS485 library does not include a `virtual size_t write(const uint8_t *buffer, size_t size);` method. Just like the existing `virtual size_t write(uint8_t value);`, this method must run `enableTx()`. Otherwise the RS485 transceiver will not transmit any data. Both these methods are used by the `ModbusRTUMaster` class.
2. In `void RS485Class::begin(unsigned long baud, uint8_t duplex, uint32_t config)` the code;
```cpp
uart_isr_free(RS485_HWSERIAL);
uart_isr_register(RS485_HWSERIAL, rs485_isr, this, ESP_INTR_FLAG_IRAM, nullptr);
```
causes the CPU to crash whenever it receives data from the RS485 transceiver.

```text
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d5439  PS      : 0x00060330  A0      : 0x800d1195  A1      : 0x3ffb1f30
A2      : 0x00000002  A3      : 0x00000000  A4      : 0x0800001e  A5      : 0x00000003
A6      : 0x00000001  A7      : 0x00000000  A8      : 0x800d1108  A9      : 0x3ffb1ef0
A10     : 0x3ffbfef8  A11     : 0x00004b00  A12     : 0x0800001e  A13     : 0x00000010
A14     : 0x00000011  A15     : 0x00000000  SAR     : 0x0000000f  EXCCAUSE: 0x0000001c
EXCVADDR: 0x0000000c  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000

Backtrace: 0x400d5439:0x3ffb1f30 0x400d1192:0x3ffb1f60 0x400d0d08:0x3ffb1f80 0x400d1736:0x3ffb1fb0 0x40085a79:0x3ffb1fd0
```
This is not due to something strange in my code as this also occurs with `examples/Receive/Receive.ino` .

To fix both problems I had to patch the code. I solved the first issue by implementing the missing method. The second, I solved by disabling the code that causes the crash. Then I added `flush()` operations to empty the output buffer before performing a `disableTx()`. A better solution would be to figure out why the `uart_isr_*` code isn't working. Something I don't have to time to do right now.

The code can be found at https://github.com/ganehag/industrialshields-rs485/

**Comment by areyal** [comment]
Same problem. rs485_isr is crashing, checked with ESP Exception Decoder.
Thank you for sharing your findings. I was about to give up.
