### ISSUE TITLE
ModbusTCPSlave Example Won't compile

### ISSUE THREAD

**Issue by kethort** [IndustrialShields/arduino-Tools40#3]
Fresh install of latest Arduino software and latest update to the Tools40 from github.

`'ModbusTCPSlave' does not name a type; did you mean 'ModbusSlave'?`

I'm not sure why you closed the last issue when it didn't get fixed.

**Comment by jordicasals** [comment]
Dear kethort,

could you tell us the board/device you are using? Nowadays, both the ModbusTCPMaster and ModbusTCPSlave libraries are only available for M-Duino devices.

We are using the included example (examples/Modbus/ModbusTCPSlave/ModbusTCPSlave.ino) and it seems to work correctly in the last Arduino IDE version (1.8.10) and an M-Duino 21+ board. Could you send us the whole compilation output? Remember to enable both the build and install outputs in the Preferences menu.

Thank you,
