### ISSUE TITLE
ModbusTCPSlave example does not work

### ISSUE THREAD

**Issue by SorenBNielsen** [IndustrialShields/arduino-Tools40#4]
I have installed tools40 and want to use the ModbusTCPSlave example. 
When I compile it, I get the error: 
'ModbusTCPSlave' does not name a type; did you mean 'ModbusSlave'?

I can see that others get the same error. 

Do you have any ideas why your code does not compile ?

**Comment by jordicasals** [comment]
Hi, 

Here is the response:
https://github.com/IndustrialShields/arduino-Tools40/issues/3#issuecomment-575833699
